### ISSUE TITLE
conn.Read return value is ambiguous

### ISSUE THREAD

**Issue by Fasjeit** [mimoo/disco#11]
Looks like int return value can be either the number of **output** bytes, written to output buffer, or in case of exception, number of **input** bytes, read from socket, including length. 

In case of correct decryption this output helps user truncate the buffer and get correct output, 
But in case of exception I don't see any useful ways to utilize this integer return value.

So, is this ambiguity intended, and if so why user need it? Maybe it will be better just return 0 for all exceptions?

**Comment by mimoo** [comment]
Hey @Fasjeit. Thanks for pointing that out https://github.com/mimoo/disco/blob/master/libdisco/conn.go#L132:L217

I tried to mirror crypto/tls code but noticed that it often returned 0 when there was an error. https://github.com/golang/go/blob/master/src/crypto/tls/conn.go#L1124:L1191

I thought we could be more useful and use that return value even when there is an error. But indeed I do not know exactly how it could be useful.

**Comment by Fasjeit** [comment]
Looks like in tls non-zero return value is obtained here
```go 
n, err = c.input.Read(b)
```
so output value n in this case is always related to output value. Basically it means "we managed to read something from input connection before, here is your data, here is it's length, but looks like there is an error when we are trying to read more."

In case of disco we return 
```go 
return 2 + length, errors.New("disco: cannot decrypt the payload")
```
which not only does no good to user, but also preventing him from getting correct length of data, stored in buffer b after function call. It means "there is an error, we are not going to tell you how to truncate the buffer b to get at least some data we cached before, but instead here is the number of raw bytes from connection we managed to read."

If you want to copy tls it will probably be better to return readSoFar value in case of errors, so user can get correct data length, if it was read from inputBuffer.

```go
// read whatever there is to read in the buffer
	readSoFar := 0
	if len(c.inputBuffer) > 0 {
		copy(b, c.inputBuffer)
		if len(c.inputBuffer) >= len(b) {
			c.inputBuffer = c.inputBuffer[len(b):]
			return len(b), nil
		}
		readSoFar += len(c.inputBuffer)
		c.inputBuffer = c.inputBuffer[:0]
        }

	// read header from socket
	bufHeader, err := readFromUntil(c.conn, 2)
	if err != nil {
                // already read readSoFar bytes to b
		return readSoFar, err
        }

        // -> same thing for errors below
```

**Comment by mimoo** [comment]
Ah I see what you mean, there is a difference between:

* we read `n` bytes (which is what we're doing here)
* we filled `n` bytes in the `b` buffer passed as argument to the function.

```go
func (c *Conn) Read(b []byte) (n int, err error) {
```

In this case I think it makes sense to apply the change you're proposing (do you want to make a PR? Otherwise I can do it)

Or are you thinking of something else?
