### ISSUE TITLE
Website has no HTTPS (redirect)

### ISSUE THREAD

**Issue by rugk** [mimoo/disco#38]
## What's wrong 

http://www.discocrypto.com/

## How it should be

https://www.discocrypto.com/by default

## Why?

Obviously, it is not really good for a **crypto** lib not to force the use of HTTPS on their website. See also: HSTS. :wink:

**Comment by mimoo** [comment]
Hey @rugk 

There is HTTPS but indeed I forgot to enable HSTS. This is fixed now. Thanks for reporting this.
