### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by zabbal** [mimoo/disco#50]
What's the license for library as well as other code in this repo? Would be nice to have explicit license/copying file and SPDX tags inside source files.

**Comment by mimoo** [comment]
not knowing much about license, do you have a suggestion?

**Comment by zabbal** [comment]
Well, my personal preference is GPLv3+, see https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3) for details.
https://tldrlegal.com/ - this might be of some help while making a choice: ultimately it's your (and all other contributor's) decision.

**Comment by mimoo** [comment]
My only worries is that I pick up a license that brushes people the wrong way. So I'd rather pick up the most permissive one. Can I invent my own license and write a file here that says "do whatever you want"?

**Comment by Fasjeit** [comment]
You can also look at MIT: https://opensource.org/licenses/MIT

... or even http://www.wtfpl.net/about/ :)

**Comment by mimoo** [comment]
this MIT thing is not great though:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by mimoo** [comment]
argg, I'll just make my own license.

**Comment by mimoo** [comment]
please tell me this works o.o https://github.com/mimoo/disco/blob/master/LICENSE

**Comment by Fasjeit** [comment]
More Licenses to the License God! :)
![img](https://i.imgur.com/HWrQC4N.jpg)

**Comment by zabbal** [comment]
> argg, I'll just make my own license.

Well, you've just brushed away anyone who have to use FOSS as legally defined by being "under OSI-approved license" [1]. Granted, that definitition is not ubiquitous so it's still OK for plenty of people. Alas, not my code - not my decision.

[1] https://opensource.org/

**Comment by mimoo** [comment]
Alright, will put a BSD-0 then
